"""empty message

Revision ID: ab1fd1b1a8e3
Revises: 
Create Date: 2019-12-08 11:41:47.932878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1fd1b1a8e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('songLink', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Band_name'), 'Band', ['name'], unique=True)
    op.create_table('Porch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('band', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('bandID', sa.Integer(), nullable=True),
    sa.Column('porchID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bandID'], ['Band.id'], ),
    sa.ForeignKeyConstraint(['porchID'], ['Porch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Event_time'), 'Event', ['time'], unique=False)
    op.create_table('UserToBand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('bandID', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('owns', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bandID'], ['Band.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserToBand')
    op.drop_index(op.f('ix_Event_time'), table_name='Event')
    op.drop_table('Event')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('Porch')
    op.drop_index(op.f('ix_Band_name'), table_name='Band')
    op.drop_table('Band')
    # ### end Alembic commands ###
